### ISSUE TITLE
Segmentation fault on empty points

### ISSUE THREAD

**Issue by STNLd2** [storpipfugl/pykdtree#116]
Please add a check for empty point array in `KDTree` input.
```python
tree = KDTree(np.array([]))
```
falls with the segmentation fault.

**Comment by mraspaud** [comment]
@STNLd2 thanks for bring this to our attention! is this anything you are willing to provide a fix for?

**Comment by djhoese** [comment]
@STNLd2 I know that @mraspaud is getting ready to go on holiday so he might not have time for this. I know I don't right now either. Since you found the issue, filed the bug, and have the use case where you'd like this check, it may be best for you to tackle this. And it wouldn't be just 2 lines of code because this could use a test in the test_tree.py module too.

**Comment by STNLd2** [comment]
Sorry, I've just noticed the last message.
I see. I'll do it.
